version: '2'

networks:
  fabric_network:
    external: false

services:

  ca.org1.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA_SERVER_PRIVATE_KEY.pem
    ports:
      - "7054:7054"
    networks:
      - fabric_network

  peer0.org1.example.com:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_ALLOWOTHERPEERS=true
      - CORE_VM_DOCKER_HOST=unix:///var/run/docker.sock
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
    ports:
      - "7051:7051"
    volumes:
      - peer0.org1.example.com:/etc/hyperledger/fabric
    networks:
      - fabric_network

  orderer.example.com:
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_TLS_ENABLED=true
      - ORDERER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - ORDERER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - ORDERER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    ports:
      - "7050:7050"
    volumes:
      - orderer.example.com:/var/hyperledger/orderer
    networks:
      - fabric_network

  couchdb:
    image: hyperledger/fabric-couchdb
    ports:
      - "5984:5984"
    networks:
      - fabric_network

volumes:
  peer0.org1.example.com:
  orderer.example.com:
